// Visual workflow authoring and smart forms. Authorization and graph execution
// belong to the server; node positions only control the presentation here.
'use strict';
const WorkflowUI = (() => {
  let scriptLocked=false;
  let definitions=[],types=[],people=[],statuses=[],definition=null,selected=null,connectFrom=null,run=null;
  const drafts=new Map();
  const kinds=['start','form','review','check','script','status','fork','join','end'];
  const split=text=>text.split(',').map(s=>s.trim()).filter(Boolean);
  const root=()=>$('view-workflow-editor');
  function mark(){drafts.set(definition.id || 'new',structuredClone(definition));$('wf-saved').textContent='Unsaved changes';}
  async function load(){[definitions,types,statuses]=await Promise.all([api('GET','/api/workflows'),api('GET','/api/part-types'),api('GET','/api/settings')]);scriptLocked=statuses.script_editor_locked || !statuses.script_editor_enabled;statuses=statuses.status_options;}
  const options=(values,selected)=>values.map(v=>`<option value="${escape(v)}" ${v===selected?'selected':''}>${escape(v)}</option>`).join('');
  function fieldInput(field,value,editable,required=false,scope='') {
    const id=`wf-field-${scope}-${field.key}`,common=`data-field="${escape(field.key)}" id="${escape(id)}" ${editable?'':'disabled'} ${required && field.kind!=='boolean'?'required':''}`;
    let control;
    if(field.kind==='boolean')control=`<input type="checkbox" ${common} ${value===true?'checked':''}>`;
    else if(field.kind==='textarea')control=`<textarea ${common}>${escape(value || '')}</textarea>`;
    else if(field.kind==='choice')control=`<select ${common}><option value="">Choose…</option>${options(field.choices,value)}</select>`;
    else control=`<input type="${field.kind==='number'?'number':'text'}" ${field.kind==='number'?'step="any"':''} ${common} value="${escape(value ?? '')}">`;
    return `<label for="${escape(id)}">${escape(field.label)}${required?' *':''}${control}</label>`;
  }
  function readFields(container) {
    const values={};container.querySelectorAll('[data-field]:not(:disabled)').forEach(el=>{
      if(el.type==='checkbox')values[el.dataset.field]=el.checked;
      else values[el.dataset.field]=el.value===''?null:el.type==='number'?Number(el.value):el.value;
    });return values;
  }
  async function list() {
    await load();const runs=await api('GET','/api/workflow-runs');
    $('view-workflows').innerHTML=`<div class="toolbar"><h1>Workflows</h1>${me.is_admin?'<a class="button" href="#/workflow-editor/new">Create workflow</a>':''}</div><p>Start a release, change request or other process. Your tasks appear in the Inbox.</p><div class="workflow-list">${definitions.filter(d=>d.active).map(d=>`<article><h2>${escape(d.name)}</h2><p>${escape(d.description)}</p><small>${escape(d.kind)} · ${d.part_types.length?d.part_types.map(id=>escape(types.find(t=>t.id===id)?.name || id)).join(', '):'All part types'}</small><div>${me.is_admin || d.can_start?`<button data-start="${escape(d.id)}">Start</button>`:''}${me.is_admin?`<a href="#/workflow-editor/${encodeURIComponent(d.id)}">Edit</a>`:''}</div></article>`).join('')}</div>${me.is_admin?`<p>Inactive definitions: ${definitions.filter(d=>!d.active).map(d=>`<a href="#/workflow-editor/${encodeURIComponent(d.id)}">${escape(d.name)}</a>`).join(', ') || 'None'}</p>`:''}<h2>Process monitor</h2><table><thead><tr><th>Process</th><th>Workflow</th><th>Status</th><th>Initiator</th><th>Started</th></tr></thead><tbody>${runs.map(r=>`<tr><td><a href="#/workflow-run/${encodeURIComponent(r.id)}">${escape(r.title)}</a></td><td>${escape(r.workflow)} v${r.version}</td><td>${escape(r.state)}</td><td>${escape(r.initiator)}</td><td>${escape(when(r.created_at))}</td></tr>`).join('')}</tbody></table><div id="wf-start-panel"></div>`;
    $('view-workflows').querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>act(()=>startForm(b.dataset.start)));
  }
  async function startForm(id) {
    const d=definitions.find(d=>d.id===id);const result=await api('GET','/api/parts?limit=1000');const parts=result.parts || result;
    const eligible=parts.filter(p=>!d.part_types.length || d.part_types.includes(p.part_type));
    $('wf-start-panel').innerHTML=`<form id="wf-start-form"><h2>Start ${escape(d.name)}</h2><label>Title<input id="wf-title" value="${escape(d.name)}" required maxlength="200"></label><label>Part<select id="wf-part"><option value="">No part</option>${eligible.map(p=>`<option value="${escape(p.id)}">${escape(p.number)} · ${escape(p.name)}</option>`).join('')}</select></label><label>Revision<select id="wf-revision"><option value="">Newest revision</option></select></label>${d.fields.map(f=>fieldInput(f,'',true,f.required_at.includes('start'))).join('')}<button type="submit">Start process</button></form>`;
    $('wf-part').onchange=()=>act(async()=>{const id=$('wf-part').value;if(!id){$('wf-revision').innerHTML='<option value="">Newest revision</option>';return;}const part=await api('GET',`/api/parts/${encodeURIComponent(id)}`);$('wf-revision').innerHTML=part.revision_views.map(r=>`<option value="${escape(r.id)}">${escape(r.label)} · ${escape(statusName(r.lifecycle))}</option>`).join('');});
    $('wf-start-form').onsubmit=e=>{e.preventDefault();const button=e.submitter;button.disabled=true;act(async()=>{try{const result=await api('POST','/api/workflow-runs',{workflow:id,title:$('wf-title').value,part:$('wf-part').value,revision:$('wf-revision').value,fields:readFields($('wf-start-form'))});location.hash=`#/workflow-run/${encodeURIComponent(result.id)}`;await refreshInbox();}finally{button.disabled=false;}});};
    $('wf-start-panel').scrollIntoView();
  }
  function starter(template='general') {
    const node=(id,label,kind,x,y,extra={})=>({id,label,kind,x,y,assignees:[],approvals:0,allow_self_review:false,code:'',status:null,...extra});
    const d={id:'',name:template==='release'?'Part release':template==='change_request'?'Change request':'New workflow',description:'',kind:template,active:true,require_for_release:false,part_types:[],start_groups:['group:author'],version:0,updated_by:'',updated_at:0,fields:[{key:'reason',label:'Reason',kind:'textarea',choices:[],required_at:['start'],readers:['*'],writers:['initiator']}],nodes:[node('start','Start','start',40,160),node('request','Complete request','form',280,160,{assignees:['initiator']}),node('end','Complete','end',560,160)],edges:[{from:'start',to:'request',on:'always'},{from:'request',to:'end',on:'always'}]};
    if(template==='release') {
      d.nodes=[node('start','Start','start',30,180),node('review','Parallel model review','review',270,70,{assignees:['group:checkin']}),node('check','Automated check','check',270,300,{code:'function step(input) {\n  const part = plm.part(input.partId);\n  if (!part.description) throw new Error("Add a part description before release.");\n  return { outcome: "success" };\n}'}),node('join','Wait for all checks','join',540,180),node('release','Release model','status',780,180,{status:'released'}),node('end','Released','end',1020,180),node('reject','Rejected','end',540,420)];
      d.edges=[{from:'start',to:'review',on:'always'},{from:'start',to:'check',on:'always'},{from:'review',to:'join',on:'success'},{from:'check',to:'join',on:'success'},{from:'join',to:'release',on:'success'},{from:'release',to:'end',on:'success'},{from:'review',to:'reject',on:'reject'},{from:'check',to:'reject',on:'reject'}];
    }
    return d;
  }
  async function editor(id) {
    await load();people=await api('GET','/api/users');
    definition=drafts.get(id) || (id==='new'?starter():structuredClone(definitions.find(d=>d.id===id)));
    if(!definition)throw new Error('Workflow does not exist');selected=null;connectFrom=null;
    root().innerHTML=`<div class="toolbar"><h1>Workflow editor</h1><a href="#/workflows">Processes</a><button id="wf-save">Save workflow</button><span id="wf-saved"></span></div><div class="workflow-meta"><label>Name<input id="wf-name" value="${escape(definition.name)}" maxlength="200"></label><label>Description<input id="wf-description" value="${escape(definition.description)}"></label><label>Purpose<select id="wf-purpose">${options(['general','release','change_request'],definition.kind)}</select></label><label><input id="wf-active" type="checkbox" ${definition.active?'checked':''}>Available to start</label><label id="wf-required-release-label" ${definition.kind==='release'?'':'hidden'}><input id="wf-required-release" type="checkbox" ${definition.require_for_release?'checked':''}>Require this workflow for part release</label><label>Allowed part types<select id="wf-types" multiple>${types.map(t=>`<option value="${escape(t.id)}" ${definition.part_types.includes(t.id)?'selected':''}>${escape(t.name)}</option>`).join('')}</select><small>No selection allows all types.</small></label><label>Who can start<input id="wf-starters" value="${escape(definition.start_groups.join(', '))}"><small>user:username, group:name, or *; empty allows authors.</small></label>${id==='new'?'<label>Template<select id="wf-template"><option value="general">Smart form</option><option value="release">Part release with parallel review and check</option><option value="change_request">Change request</option></select></label>':''}</div>
      <p>Drag a step from the palette onto the canvas. Drag existing steps to move them. Click an output connector, then an input connector, to create a path. Select a step to edit it.</p><div class="workflow-editor-layout"><aside id="wf-palette">${kinds.map(kind=>`<button type="button" draggable="true" data-kind="${kind}">${escape(kind)}</button>`).join('')}</aside><div class="workflow-canvas-scroll"><div id="wf-canvas" tabindex="0" aria-label="Workflow process canvas"><svg id="wf-paths" aria-label="Workflow paths"></svg><div id="wf-nodes"></div></div></div><aside id="wf-properties"><p>Select a step.</p></aside></div>
      <h2>Paths</h2><p>“always” selects a path for any completed outcome; success, reject or a JavaScript outcome name selects a conditional path.</p><div id="wf-edge-list"></div>
      <h2>Form fields</h2><p>Permissions use user:username, group:name, initiator, assignee or *. Required at accepts start or step IDs. Fields can become required later in the process.</p><div id="wf-fields"></div><button id="wf-add-field">Add field</button>`;
    ['name','description','purpose','active','types','starters','required-release'].forEach(key=>$(`wf-${key}`).onchange=()=>{definition.name=$('wf-name').value;definition.description=$('wf-description').value;definition.kind=$('wf-purpose').value;$('wf-required-release-label').hidden=definition.kind!=='release';if(definition.kind!=='release')$('wf-required-release').checked=false;definition.active=$('wf-active').checked;definition.require_for_release=$('wf-required-release').checked;definition.part_types=[...$('wf-types').selectedOptions].map(o=>o.value);definition.start_groups=split($('wf-starters').value);mark();});
    if($('wf-template'))$('wf-template').onchange=()=>{definition=starter($('wf-template').value);drafts.set('new',definition);act(()=>editor('new'));};
    $('wf-save').onclick=()=>act(async()=>{definition=await api('POST','/api/workflows',definition);drafts.delete(id);drafts.delete('new');$('wf-saved').textContent=`Saved version ${definition.version}`;OpenPages.saved();if(id==='new')location.hash=`#/workflow-editor/${encodeURIComponent(definition.id)}`;});
    $('wf-palette').querySelectorAll('[data-kind]').forEach(button=>{button.ondragstart=e=>e.dataTransfer.setData('application/x-plm-workflow-node',button.dataset.kind);button.onclick=()=>addNode(button.dataset.kind,100,100);});
    const canvas=$('wf-canvas');canvas.ondragover=e=>e.preventDefault();canvas.ondrop=e=>{e.preventDefault();const kind=e.dataTransfer.getData('application/x-plm-workflow-node');if(!kinds.includes(kind))return;const rect=canvas.getBoundingClientRect();addNode(kind,e.clientX-rect.left,e.clientY-rect.top);};
    $('wf-add-field').onclick=()=>{definition.fields.push({key:`field${definition.fields.length+1}`,label:'New field',kind:'text',choices:[],required_at:[],readers:['*'],writers:['initiator']});mark();drawFields();};
    drawGraph();drawEdges();drawFields();
  }
  function addNode(kind,x,y) {
    let index=definition.nodes.length+1;while(definition.nodes.some(n=>n.id===`step${index}`))index++;
    const node={id:`step${index}`,label:kind,kind,x:Math.max(10,x),y:Math.max(10,y),assignees:['initiator'],approvals:0,allow_self_review:false,code:'function step(input) {\n  return { outcome: "success", fields: {} };\n}',status:kind==='status'?'released':null};
    definition.nodes.push(node);selected=node.id;mark();drawGraph();properties();
  }
  function drawGraph() {
    const width=Math.max(1200,...definition.nodes.map(n=>n.x+240)),height=Math.max(600,...definition.nodes.map(n=>n.y+140));
    $('wf-canvas').style.width=`${width}px`;$('wf-canvas').style.height=`${height}px`;
    $('wf-nodes').innerHTML=definition.nodes.map(n=>`<div class="workflow-node ${n.id===selected?'selected':''}" data-node="${escape(n.id)}" tabindex="0" role="group" aria-label="${escape(n.label)}"><button class="wf-port input" data-input="${escape(n.id)}" title="Connect into ${escape(n.label)}" aria-label="Connect into ${escape(n.label)}">●</button><div class="wf-node-handle"><small>${escape(n.kind)} · ${escape(n.id)}</small><strong>${escape(n.label)}</strong></div><button class="wf-port output" data-output="${escape(n.id)}" title="Connect from ${escape(n.label)}" aria-label="Connect from ${escape(n.label)}">●</button></div>`).join('');
    $('wf-nodes').querySelectorAll('[data-node]').forEach(el=>{
      const position=definition.nodes.find(n=>n.id===el.dataset.node);el.style.left=`${position.x}px`;el.style.top=`${position.y}px`;
      el.onclick=e=>{if(e.target.closest('.wf-port'))return;selected=el.dataset.node;root().querySelectorAll('[data-node]').forEach(n=>n.classList.toggle('selected',n===el));properties();};
      el.onkeydown=e=>{const node=definition.nodes.find(n=>n.id===el.dataset.node);if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();node.x=Math.max(10,node.x+({ArrowLeft:-10,ArrowRight:10}[e.key]||0));node.y=Math.max(10,node.y+({ArrowUp:-10,ArrowDown:10}[e.key]||0));el.style.left=`${node.x}px`;el.style.top=`${node.y}px`;mark();paths();}if(e.key==='Enter'){selected=node.id;properties();}};
      el.querySelector('.wf-node-handle').onpointerdown=e=>{if(e.button!==0)return;const node=definition.nodes.find(n=>n.id===el.dataset.node),start={x:e.clientX,y:e.clientY,nx:node.x,ny:node.y};e.target.setPointerCapture(e.pointerId);const move=ev=>{node.x=Math.max(10,start.nx+ev.clientX-start.x);node.y=Math.max(10,start.ny+ev.clientY-start.y);el.style.left=`${node.x}px`;el.style.top=`${node.y}px`;paths();};const end=()=>{e.target.removeEventListener('pointermove',move);e.target.removeEventListener('pointerup',end);e.target.removeEventListener('pointercancel',end);mark();};e.target.addEventListener('pointermove',move);e.target.addEventListener('pointerup',end);e.target.addEventListener('pointercancel',end);};
    });
    $('wf-nodes').querySelectorAll('[data-output]').forEach(b=>b.onclick=()=>{connectFrom=b.dataset.output;$('wf-saved').textContent=`Choose an input for ${connectFrom}`;});
    $('wf-nodes').querySelectorAll('[data-input]').forEach(b=>b.onclick=()=>{if(!connectFrom || connectFrom===b.dataset.input)return;definition.edges.push({from:connectFrom,to:b.dataset.input,on:'always'});connectFrom=null;mark();paths();drawEdges();});paths();
  }
  function paths() {
    $('wf-paths').innerHTML='<defs><marker id="wf-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8" fill="#468bc4" stroke="none"/></marker></defs>'+definition.edges.map(e=>{const from=definition.nodes.find(n=>n.id===e.from),to=definition.nodes.find(n=>n.id===e.to);if(!from || !to)return '';const x1=from.x+180,y1=from.y+42,x2=to.x,y2=to.y+42,dx=Math.max(60,Math.abs(x2-x1)/2);return `<g><path marker-end="url(#wf-arrow)" d="M ${x1} ${y1} C ${x1+dx} ${y1}, ${x2-dx} ${y2}, ${x2} ${y2}"/><text x="${(x1+x2)/2}" y="${(y1+y2)/2-8}">${escape(e.on)}</text></g>`;}).join('');
  }
  function properties() {
    const node=definition.nodes.find(n=>n.id===selected);if(!node)return;
    $('wf-properties').innerHTML=`<h2>Step properties</h2><p>Step ID: ${escape(node.id)}</p><label>Name<input id="wf-node-name" value="${escape(node.label)}"></label><label>Kind<select id="wf-node-kind">${options(kinds,node.kind)}</select></label>${['form','review'].includes(node.kind)?`<label>Assignees<input id="wf-node-assignees" value="${escape(node.assignees.join(', '))}"><small>user:username, group:name or initiator. Available users: ${people.map(u=>escape(u.username)).join(', ')}</small></label>`:''}${node.kind==='review'?`<label>Required approvals<input id="wf-node-approvals" type="number" min="0" value="${node.approvals}"><small>0 requires all assigned reviewers, in parallel.</small></label><label><input id="wf-node-self" type="checkbox" ${node.allow_self_review?'checked':''}>Allow initiator to review</label>`:''}${node.kind==='status'?`<label>Lifecycle status<select id="wf-node-status">${statuses.filter(s=>s.enabled && s.state!=='superseded').map(s=>`<option value="${escape(s.state)}" ${s.state===node.status?'selected':''}>${escape(s.name)}</option>`).join('')}</select></label>`:''}${['script','check'].includes(node.kind)?`<label>JavaScript<textarea id="wf-node-code" rows="14" spellcheck="false" ${scriptLocked?'readonly':''}>${escape(node.code)}</textarea></label><small>Define step(input). Return { outcome, fields }, or false for reject; throw to stop with an error. input includes fields, partId, revisionId and idempotencyKey. Trusted scripts can use http.request, plm, fs and process.</small><label>Example<select id="wf-script-example" ${scriptLocked?'disabled':''}><option value="">Choose an example</option><option value="check">Model check</option><option value="erp">ERP order</option><option value="pdf">Publish vendor PDF</option></select></label>`:''}<button id="wf-delete-node" class="danger">Delete step</button>`;
    const update=()=>{node.label=$('wf-node-name').value;node.kind=$('wf-node-kind').value;if($('wf-node-assignees'))node.assignees=split($('wf-node-assignees').value);if($('wf-node-approvals'))node.approvals=Number($('wf-node-approvals').value);if($('wf-node-self'))node.allow_self_review=$('wf-node-self').checked;if($('wf-node-status'))node.status=$('wf-node-status').value;if($('wf-node-code'))node.code=$('wf-node-code').value;if(node.kind==='status'&&!node.status)node.status='released';mark();drawGraph();};
    $('wf-properties').querySelectorAll('input,select,textarea').forEach(el=>el.onchange=()=>{update();if(el.id==='wf-node-kind')properties();});
    if($('wf-script-example'))$('wf-script-example').onchange=()=>{
      const examples={check:'function step(input) {\n  const document = plm.readDocument(input.partId, input.revisionId);\n  if (!document) throw new Error("Model document is missing");\n  return { outcome: "success" };\n}',erp:'function step(input) {\n  // Configure your ERP endpoint and authentication on this server.\n  const url = "";\n  if (!url) throw new Error("Configure the ERP endpoint");\n  const response = http.request({ url, method: "POST", headers: { "Idempotency-Key": input.idempotencyKey }, body: JSON.stringify({ part: input.partId, quantity: input.fields.quantity }) });\n  if (response.status >= 400) throw new Error("ERP order failed");\n  return { outcome: "success" };\n}',pdf:'function step(input) {\n  // Generate/export the PDF in an earlier step, then publish its bytes.\n  const url = "";\n  if (!url) throw new Error("Configure the vendor catalog endpoint");\n  const pdf = fs.readBase64(input.fields.pdfPath);\n  const response = http.request({ url, method: "PUT", headers: { "Content-Type": "application/pdf", "Idempotency-Key": input.idempotencyKey }, body_base64: pdf });\n  if (response.status >= 400) throw new Error("Catalog publication failed");\n  return { outcome: "success" };\n}'};
      node.code=examples[$('wf-script-example').value] || node.code;$('wf-node-code').value=node.code;mark();
    };
    $('wf-delete-node').onclick=()=>{definition.nodes=definition.nodes.filter(n=>n.id!==node.id);definition.edges=definition.edges.filter(e=>e.from!==node.id && e.to!==node.id);selected=null;mark();drawGraph();drawEdges();$('wf-properties').innerHTML='<p>Select a step.</p>';};
  }
  function drawEdges() {
    $('wf-edge-list').innerHTML=definition.edges.map((e,i)=>`<div class="workflow-edge-row"><span>${escape(e.from)} → ${escape(e.to)}</span><label>Outcome<input data-edge="${i}" value="${escape(e.on)}" aria-label="Outcome for ${escape(e.from)} to ${escape(e.to)}"></label><button data-delete-edge="${i}">Remove path</button></div>`).join('');
    $('wf-edge-list').querySelectorAll('[data-edge]').forEach(el=>el.onchange=()=>{definition.edges[Number(el.dataset.edge)].on=el.value.trim();mark();paths();});
    $('wf-edge-list').querySelectorAll('[data-delete-edge]').forEach(el=>el.onclick=()=>{definition.edges.splice(Number(el.dataset.deleteEdge),1);mark();drawEdges();paths();});
  }
  function drawFields() {
    $('wf-fields').innerHTML=definition.fields.map((f,i)=>`<fieldset data-form-field="${i}"><legend>${escape(f.label)}</legend>${[['key','Key'],['label','Label'],['choices','Choice options'],['required_at','Required at'],['readers','Can read'],['writers','Can edit']].map(([key,label])=>`<label>${label}<input data-property="${key}" value="${escape(Array.isArray(f[key])?f[key].join(', '):f[key])}"></label>`).join('')}<label>Type<select data-property="kind">${options(['text','textarea','number','boolean','choice'],f.kind)}</select></label><button data-remove-field="${i}">Remove field</button></fieldset>`).join('');
    $('wf-fields').querySelectorAll('[data-property]').forEach(el=>el.onchange=()=>{const field=definition.fields[Number(el.closest('[data-form-field]').dataset.formField)],key=el.dataset.property;field[key]=['choices','required_at','readers','writers'].includes(key)?split(el.value):el.value;mark();});
    $('wf-fields').querySelectorAll('[data-remove-field]').forEach(el=>el.onclick=()=>{definition.fields.splice(Number(el.dataset.removeField),1);mark();drawFields();});
  }
  async function detail(id) {
    run=await api('GET',`/api/workflow-runs/${encodeURIComponent(id)}`);
    const waiting=run.definition.nodes.filter(n=>run.steps[n.id].state==='waiting' && run.steps[n.id].assignees.includes(me.id) && !run.steps[n.id].decisions.some(d=>d.user_id===me.id));
    $('view-workflow-run').innerHTML=`<div class="toolbar"><h1>${escape(run.title)}</h1><a href="#/workflows">Process monitor</a><button id="wf-refresh-run">Refresh</button></div><p>${escape(run.definition.name)} v${run.definition.version} · ${escape(run.state)} · started by ${escape(run.initiator_name)}</p>${run.part?`<a href="#/part/${encodeURIComponent(run.part)}/${encodeURIComponent(run.revision)}">Open target model</a>`:''}<ol class="workflow-progress">${run.definition.nodes.map(n=>`<li><strong>${escape(n.label)}</strong> <span>${escape(run.steps[n.id].state)}</span>${run.steps[n.id].decisions.length?`<small>${run.steps[n.id].decisions.map(d=>`${escape(d.username)}: ${escape(d.outcome)}`).join(', ')}</small>`:''}${me.is_admin && run.steps[n.id].state==='failed'?`<button data-retry="${escape(n.id)}">Retry failed step</button>`:''}</li>`).join('')}</ol>
      <div id="wf-task-forms">${waiting.map(n=>`<form data-task="${escape(n.id)}"><h2>${escape(n.label)}</h2><p>${n.kind==='review'?'Review the target model and record your decision. Each assigned reviewer responds independently.':'Complete the fields required for this step.'}</p>${run.definition.fields.map(f=>fieldInput(f,run.fields[f.key],f.can_edit,f.required_at.includes(n.id),n.id)).join('')}<label>Comment<textarea data-comment></textarea></label><button type="submit" data-outcome="success">${n.kind==='review'?'Approve':'Complete'}</button><button type="submit" data-outcome="reject" formnovalidate>Reject</button></form>`).join('')}</div>${waiting.length?'':`<h2>Form values</h2>${run.definition.fields.map(f=>fieldInput(f,run.fields[f.key],false)).join('')}`}
      ${['active','blocked'].includes(run.state)&&(me.is_admin||run.initiator===me.id)?'<button id="wf-cancel-run" class="danger">Cancel process</button>':''}<h2>Workflow history</h2><table><thead><tr><th>Time</th><th>Step</th><th>Event</th><th>User</th><th>Detail</th></tr></thead><tbody>${run.log.map(e=>`<tr><td>${escape(when(e.at))}</td><td>${escape(run.definition.nodes.find(n=>n.id===e.node)?.label || e.node)}</td><td>${escape(e.action)}</td><td>${escape(e.username)}</td><td>${escape(e.message)}</td></tr>`).join('')}</tbody></table>`;
    $('wf-refresh-run').onclick=()=>act(()=>detail(id));
    $('wf-task-forms').querySelectorAll('form').forEach(form=>form.onsubmit=e=>{e.preventDefault();act(async()=>{await api('POST',`/api/workflow-runs/${encodeURIComponent(id)}/actions`,{node:form.dataset.task,outcome:e.submitter.dataset.outcome,comment:form.querySelector('[data-comment]').value,fields:readFields(form)});await detail(id);await refreshInbox();});});
    $('view-workflow-run').querySelectorAll('[data-retry]').forEach(b=>b.onclick=()=>act(async()=>{await api('POST',`/api/workflow-runs/${encodeURIComponent(id)}/control`,{action:'retry',node:b.dataset.retry});await detail(id);await refreshInbox();}));
    if($('wf-cancel-run'))$('wf-cancel-run').onclick=()=>act(async()=>{await api('POST',`/api/workflow-runs/${encodeURIComponent(id)}/control`,{action:'cancel'});await detail(id);await refreshInbox();});
  }
  return {list,editor,detail};
})();
